namespace SpriteKind {
    export const mario = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (0 == 0) {
        mario.vy = -90
    }
})
let mario: Sprite = null
mario = sprites.create(img`
    ....ffffff..............
    ..ffeeeef2f.............
    .ffeeeef222f............
    .feeeffeeeef............
    .ffffee2222ef...........
    .fe222ffffe2f...........
    fffffffeeefff...........
    ffe44ebf44eef...........
    fee4d41fddef............
    .feee4ddddf.............
    ..fdde444ef.............
    ..fdde22ccc.............
    ...eef22cdc.............
    ...f4444cddc............
    ....fffffcddc...........
    .....fff..cddc..........
    ...........cdc..........
    ............cc..........
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.mario)
controller.moveSprite(mario, 50, 0)
scene.setBackgroundColor(9)
mario.ay = 100
tiles.setCurrentTilemap(tilemap`level1`)
scene.cameraFollowSprite(mario)
